### ISSUE TITLE
Multiple Sliders with dynamic pages

### ISSUE THREAD

**Issue by trendschau** [WallopSlider/WallopSlider.js#12]
First of all thanks for this beautiful script, it could really become the __unslider without jquery__ :o)

I had a little bit hard times to work with multiple sliders on a dynamic generated page, but maybe I am missing some points.

The problem is, that you have different CSS-classes for the first slider ("photo-slider"-class) and the first image of a slider ("wallop-slider__item--current"-class). Maybe I am missing the point, but if you create the page with dynamic and optional content, you have to make a lot of counting and indexes in the backend-code (especially in the model) to differenciate between the first and the rest, and additionally you have to make some ugly if-then-that-questions in the view. This leads to quite a big code-overhead. 

Usecase: I have a blogpost with 0 images, 1 image (no slider), 2+ images (one slider) or (2+ images)+ (several sliders). This is probably a normal usecase. In the post-data I have to differentiate (which means flag it somewhere in the data) between 1 image, several images (slider) and several sliders. Hard work...

Last point: Maybe it would be easier to work with ids (for instanciating) rather than classes if it comes to multiple sliders?

Now I do it like this: 

    var allSliders = document.getElementsByClassName('wallop-slider'),
        iterations = allSliders.length;		
    for (var i=0; i < iterations; i++)
    {
        if(i > 0)
        {
            var sliderId = allSliders[i].id;
            new WallopSlider('.'+sliderId);		
        }
    }

I'm not a pro, so maybe I'm misunderstanding. And it works very good at the end, but with quite an ugly backend-code...

**Comment by peduarte** [comment]
Hey,

I've released a v2 of the slider which fixed a lot of issues, including this one!

You can now instantiate the slider with an ID. New documentation in Readme.

Thanks & sorry for the super late reply.
