### ISSUE TITLE
bower install issue

### ISSUE THREAD

**Issue by thrasnic** [WallopSlider/WallopSlider.js#27]
1. bower install wallop-slider --save
- package does not contains required files, only README and .bower

2. https://codeload.github.com/peduarte/wallop-slider/zip/exercise 
- does not exists

**Comment by fraincs** [comment]
you can do bower install --save https://github.com/WallopSlider/WallopSlider.js.git

**Comment by peduarte** [comment]
Hey,

I've released a v2 of the slider which fixed a lot of issues, including this one!

Thanks & sorry for the super late reply.
