### ISSUE TITLE
Carousel TRUE

### ISSUE THREAD

**Issue by MissFerrety** [WallopSlider/WallopSlider.js#29]
Well, I'm working with the `wSCarousel: true` setting...

Minor Issue: The website documents it as wsCarousel! (Note the lowercase "s")

## Problem
Previous button becomes disabled on first slide

### Fix

    // Update prev/next disabled attribute
    WallopProto.updatePagination = function () {
        if ((this.currentItemIndex + 1) === this.allItemsArrayLength && this.options.wSCarousel !== true) {
            this.buttonNext.setAttribute('disabled', 'disabled');
        } else if (this.currentItemIndex === 0 && this.options.wSCarousel !== true) {
            this.buttonPrevious.setAttribute('disabled', 'disabled');
        }
    };

## Problem
Classes are applied incorrectly when looping around (previous from first does not work)

### Fix

    // Callback for when previous button is clicked
    WallopProto.onPreviousButtonClicked = function () {
        if(this.currentItemIndex + 1 === 1 && this.options.wSCarousel === true) {
            this.goTo(this.allItemsArrayLength);
        } else {
            this.goTo((this.currentItemIndex + 1) - 1);
        }
    };

**Comment by peduarte** [comment]
Hey, 

I've released a v2 of the slider which fixed a lot of issues, including this one!

Thanks & sorry for the super late reply.
